{
    "name": "Lucky Tone Partner Hub Website",
    "summary": "B2B catalog, portal, ordering, samples, service, and ERP tracking",
    "version": "19.0.1.15.5",
    "category": "Website/Website",
    "license": "LGPL-3",
    "author": "Lucky Tone",
    "depends": [
        "b2b_core",
        "b2b_sample",
        "b2b_erp_connector",
        "website_sale",
        "website_cf_turnstile",
        "auth_signup",
        "phone_validation",
        "portal",
        "helpdesk",
        "helpdesk_sale",
        "repair",
    ],
    "data": [
        "security/b2b_role_security.xml",
        "security/b2b_contact_request_security.xml",
        "security/b2b_order_change_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/registration_data.xml",
        "data/registration_mail_templates.xml",
        "data/faq_data.xml",
        "views/res_config_settings_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/contact_request_views.xml",
        "views/registration_application_views.xml",
        "views/order_change_views.xml",
        "views/sale_order_views.xml",
        "views/homepage_product_views.xml",
        "views/faq_views.xml",
        "views/website_templates.xml",
        "views/vendor_branding.xml",
        "views/portal_hardening_templates.xml",
        "views/homepage_redesign.xml",
        "views/contact_templates.xml",
        "views/figma_pages.xml",
        "views/native_redesign.xml",
        "views/catalog_templates.xml",
        "views/sample_templates.xml",
        "views/service_templates.xml",
        "views/portal_templates.xml",
        "views/sale_portal_templates.xml",
        "views/checkout_templates.xml",
        "views/information_templates.xml",
        "views/portal_presentation.xml",
        "data/export_language.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "b2b_website/static/src/scss/partner_hub.scss",
            "b2b_website/static/src/js/frontend_error_branding.js",
            "b2b_website/static/src/js/turnstile_ux.js",
            "b2b_website/static/src/js/partner_hub.js",
            "b2b_website/static/src/js/payment_form.js",
        ],
    },
    "installable": True,
    "application": False,
}
